#!/bin/bash

# Fail on errors
set -e
# Show what is being done
set -x

# Supposed to be run in the chroot

# Generic system things

# Nameserver, necessary for packages fetching
echo 'nameserver 8.8.8.8' > etc/resolv.conf
TODO copy from host system instead

# Decent.im specific things

# Enable third party repos required
copy /etc/portage/repos.conf/decent-im.conf
USE=-perl emerge dev-vcs/git
emaint sync -A

# Switch to custom profile
QUESTIONABLE
#mv /etc/portage/make.profile{,.stage3}
#mkdir /etc/portage/make.profile
#cat > /etc/portage/make.profile/parent <<EOF
#/var/db/repos/gentoo/profiles/default/linux/amd64/17.1/no-multilib
#/var/db/repos/decent-im/profiles/features/decent.im
#EOF
